window:
  dynamic_padding: true
  opacity: 0.9

  # Window decorations
  #
  # Available values:
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - transparent: title bar, transparent background and title bar buttons
  # - buttonless: title bar, transparent background, but no title bar buttons
  decorations: Full

cursor:
  style: Beam

import:
  - ~/.config/alacritty/dracula.yml
