window:
  dynamic_padding: true

  # Window decorations
  #
  # Available values:
  # - full: borders and title bar
  # - none: neither borders nor title bar
  # - transparent: title bar, transparent background and title bar buttons
  # - buttonless: title bar, transparent background, but no title bar buttons
  decorations: Full

background_opacity: 0.9
cursor:
  style: Beam


schemes:
  argonaut: &argonaut
    primary:
      background: '#292C3E'
      foreground: '#EBEBEB'
    cursor:
     text: '#FF261E'
     cursor: '#FF261E'
    normal:
      black:   '#0d0d0d'
      red:     '#FF301B'
      green:   '#A0E521'
      yellow:  '#FFC620'
      blue:    '#1BA6FA'
      magenta: '#8763B8'
      cyan:    '#21DEEF'
      white:   '#EBEBEB'
    bright:
      black:   '#6D7070'
      red:     '#FF4352'
      green:   '#B8E466'
      yellow:  '#FFD750'
      blue:    '#1BA6FA'
      magenta: '#A578EA'
      cyan:    '#73FBF1'
      white:   '#FEFEF8'
  dracula: &dracula
    primary:
      background: '0x282a36'
      foreground: '0xf8f8f2'
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    search:
      matches:
        foreground: '0x44475a'
        background: '0x50fa7b'
      focused_match:
        foreground: '0x44475a'
        background: '0xffb86c'
      bar:
        background: '0x282a36'
        foreground: '0xf8f8f2'
    line_indicator:
      foreground: None
      background: None
    selection:
      text: CellForeground
      background: '0x44475a'
    normal:
      black:   '0x000000'
      red:     '0xff5555'
      green:   '0x50fa7b'
      yellow:  '0xf1fa8c'
      blue:    '0xbd93f9'
      magenta: '0xff79c6'
      cyan:    '0x8be9fd'
      white:   '0xbfbfbf'
    bright:
      black:   '0x4d4d4d'
      red:     '0xff6e67'
      green:   '0x5af78e'
      yellow:  '0xf4f99d'
      blue:    '0xcaa9fa'
      magenta: '0xff92d0'
      cyan:    '0x9aedfe'
      white:   '0xe6e6e6'
    dim:
      black:   '0x14151b'
      red:     '0xff2222'
      green:   '0x1ef956'
      yellow:  '0xebf85b'
      blue:    '0x4d5b86'
      magenta: '0xff46b0'
      cyan:    '0x59dffc'
      white:   '0xe6e6d1'

colors: *dracula
